### ISSUE TITLE
# key mapped to + on german keyboard

### ISSUE THREAD

**Issue by Tomakko** [lolo101/px1800kbd#2] opened 2016-08-23 08:37 UTC
Hi,

after installing your driver for my Perixx PX-1800 using dkms, the only key that is not working is the # key which is mapped to +.

Using `xenv` reports 

`KeyPress event, serial 37, synthetic NO, window 0x4200001,
    root 0x1e7, subw 0x0, time 513625, (-473,261), root:(962,313),
    state 0x10, keycode 35 (keysym 0x2b, plus), same_screen YES,
    XLookupString gives 1 bytes: (2b) "+"
    XmbLookupString gives 1 bytes: (2b) "+"
    XFilterEvent returns: False
`
for both keys.

Do you have a solution for this?

Thanks!

**Comment by lolo101** [comment] 2016-08-23 10:16
Hello Tomakko and thanks for your interest in this project :)
I'll take a look at your issue with the german layout as soon as possible. Thank you for the report.
Are you talking about the # key just left of the return key ? (https://en.wikipedia.org/wiki/German_keyboard_layout#/media/File:KB_Germany.svg)
You may want to try with commit 54fc3 to see if that solves the issue.

**Comment by Tomakko** [comment] 2016-08-23 10:22
Yes, its exactly that key. which is also mapped to the one directly above. I will check that commit out. Thanks for taking care of this!
Btw: Did you modify Colin Svingen's driver or is it more or less the same?

**Comment by lolo101** [comment] 2016-08-23 10:27
It's much the same, except key mappings are slighly different and I modified the installation script.

**Comment by lolo101** [comment] 2016-08-23 18:36
Hi again Tomakko.
I could reproduce your issue with the most recent version of the driver. However, I confirm that the version in commit 54fc3 seems to solve the issue.
I will try to build a new version fixing both your issue and @mgvel issue.

**Comment by lolo101** [comment] 2016-08-23 19:08
Hi again Tomakko.
I could reproduce your issue with the most recent version of the driver. However, I confirm that the version in commit 54fc3 seems to solve the issue.
I will try to build a new version fixing both your issue and @mgvel issue.

**Comment by lolo101** [comment] 2016-08-23 20:06
Please could you confirm issue resolution with the latest version ?

**Comment by Tomakko** [comment] 2016-08-24 08:27
Hey lol101!
Unfortunately i could not resolve the issue. Just to make sure i did everything right:

`~/px1800kbd$ git reset --hard 5317ace`  (tried with 54fc3, too)
`sudo ./install.sh dkms`

Afterwards, re-plugged the keyboard and restarted the computer.

Thanks again for your engagement!

**Comment by lolo101** [comment] 2016-08-24 09:18
Yes that's all you need to do.
Hmm ok i'll investigate further.

**Comment by lolo101** [comment] 2016-08-24 23:32
Tomakko, please can you uncomment the part with the `printk` instructions (lines 150-175) ?
Then reinstall the driver.
After reboot, press the faulty key, open a terminal and execute `dmesg`.
The log should end with a serie of :

```
[ 2078.727443] Keydown keycode: 4 0 128 0 0 0 0 0 
[ 2078.807414] Keyup keycode: 4 0 128 0 0 0 0 0 
[ 2078.807418] Keydown keycode: 4 0 0 0 0 0 0 0 
[ 2078.903386] Keyup keycode: 4 0 0 0 0 0 0 0 
[ 2078.903389] Keydown keycode: 5 8 0 0 0 0 0 0 
[ 2078.983362] Keyup keycode: 5 8 0 0 0 0 0 0 
[ 2078.983366] Keydown keycode: 5 0 0 0 0 0 0 0 
[ 2079.055341] Keyup keycode: 5 0 0 0 0 0 0 0 
[ 2079.055345] Keydown keycode: 4 0 0 1 0 0 0 0 
[ 2079.119322] Keyup keycode: 4 0 0 1 0 0 0 0 
[ 2079.119326] Keydown keycode: 4 0 0 0 0 0 0 0 
[ 2079.279275] Keyup keycode: 4 0 0 0 0 0 0 0 
[ 2079.279279] Keydown keycode: 4 0 0 0 64 0 0 0 
[ 2079.367251] Keyup keycode: 4 0 0 0 64 0 0 0 
[ 2079.367255] Keydown keycode: 4 0 0 0 0 0 0 0 
[ 2079.679159] Keyup keycode: 4 0 0 0 0 0 0 0 
[ 2079.679164] Keydown keycode: 4 0 0 4 0 0 0 0 
[ 2079.735142] Keyup keycode: 4 0 0 4 0 0 0 0 
[ 2079.735147] Keydown keycode: 4 0 0 0 0 0 0 0 
[ 2080.702864] Keyup keycode: 4 0 0 0 0 0 0 0 
[ 2080.702872] Keydown keycode: 4 0 0 0 0 0 0 1 
```

(This logs corresponds to the keys 'd' 'm' 'e' 's' 'g' and return)
In that way we will see what exact signal is send by the keyboard. The log you got with `xev` disturbs me a little because it show a 'keycode' 35 for both keys ('#' and '+') but as far as i understand, that code is a raw value sent by the keyboard _before_ it is converted by the driver (i don't understand where does this raw value comes from though, since it has nothing to do with signals handled by the driver).
So i want to be sure your issue is not related to a hardware issue.

**Comment by Tomakko** [comment] 2016-09-18 19:44
Hi lolo101,
i need to apologize, that i could not take care of this earlier on. 
I uncommented lines 150-175 in px1800kbd.c, reinstalled the driver and rebooted.
However i cant see any output similar to yours when executing dmesg. Only output related to the keyboard is 

`
[    8.344765] lp: driver loaded but no devices found
[    8.346076] aziokbd: module verification failed: signature and/or required key missing - tainting kernel
[    8.346187] <1>aziokbd: detected USB Keyboard
[    8.346217] input: USB Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-12/1-12:1.0/input/input8
[    8.346252] <1>aziokbd: detected USB Keyboard
[    8.346274] input: USB Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-12/1-12:1.1/input/input9
[    8.367928] usbcore: registered new interface driver aziokbd
[    8.367929] aziokbd: :Azio L70 Keyboard Driver
`

I dont want to post the log here, because i cant overview if it contains sensible information. 

Thanks again for your engagement and i promise to respond earlier now :D

**Comment by lolo101** [comment] 2016-09-19 07:10
Hi @Tomakko !

No pb, i found that `sudo showkey -s` was also very helpful. It doesn't need to you rebuild or restart anything :). It shows the KEY_\* constant mapped with the pressed key.
For your key it should show `0x2b 0xab`.
Can you confirm that's the value ?

**Comment by Tomakko** [comment] 2016-09-24 10:41
I get `0x1b 0x9b` for both the + and the # key

**Comment by lolo101** [comment] 2016-09-26 06:51
@Tomakko I wonder if the issue is not a misconfiguration of the driver instead of the driver itself.
Maybe the automatic blacklisting did not work ? Did you try the manual blacklisting procedure defined in the readme ?
Can you run the following commands ?

```
lsmod | grep usbhid
grep 0x0c45:0x7603 /etc/modprobe.d/usbhid.conf
grep 0x0c45:0x7603 /etc/grub.d/*
grep 0x0c45:0x7603 /etc/default/grub
```

**Comment by Tomakko** [comment] 2016-09-27 09:16
Hey,
so before doing anything i get 
`~$ lsmod | grep usbhid`
`usbhid                 49152  0`
`hid                   118784  3 i2c_hid,hid_generic,usbhid`
`~$ grep 0x0c45:0x7603 /etc/modprobe.d/usbhid.conf`
`options usbhid quirks=0x0c45:0x7603:0x0007`
`options usbhid quirks=0x0c45:0x7603:0x00000004`
`~$ grep 0x0c45:0x7603 /etc/grub.d/*`
`~$ grep 0x0c45:0x7603 /etc/default/grub`

Last two give no output.

According to the Readme, i modified `/etc/default/grub` and restarted, unfortunately the issue remains.

**Comment by lolo101** [comment] 2016-10-02 22:53
Hmm and just to make sure, could you execute `lsmod | grep px1800kbd` ?
I'm sorry if that seems a little redundant... I'm pretty sure the issue is with the installation and not with the driver itself, because I cannot see how two keys could return the `0x1b` (KEY_RIGHTBRACE) scancode and because `dmesg` did not return driver's logs.
Also I think you should delete the line `options usbhid quirks=0x0c45:0x7603:0x0007` from `/etc/modprobe.d/usbhid.conf` though I don't believe this is really an issue.

**Comment by Tomakko** [comment] 2016-10-06 09:19
Sounds strange.

`lsmod | grep px1800kbd` returns `px1800kbd              16384  0`

But the driver is active right? Because it correctly remapped Ctrl and Alt from Shift to their correct keys.

**Comment by Tomakko** [comment] 2016-10-11 18:47
I installed this driver before:
https://bitbucket.org/Swoogan/aziokbd

Maybe this could be relevant.

More info:
When using the ubuntu layout chart the + key is not detected at all, while the # key is shows as a +.

**Comment by lolo101** [comment] 2016-10-12 20:26
Hi Tomakko,

Yes that was the driver I tried first. But this issue https://bitbucket.org/Swoogan/aziokbd/issues/6/ convinced me to fork the driver :)
Does `aziokbd` appears in the listing of `lsmod` ?
Did you uninstall it properly with `dkms remove` ?

**Comment by lolo101** [comment] 2018-03-18 13:18
@Tomakko, could you please check if the last version of the driver and the Troubleshooting section of the readme could help you solve the issue ?

I'll close this issue unless you confirm it is still valid.

**Comment by styinx** [comment] 2018-07-30 19:02
Hi there, I just want to confirm that removing the aziokbd module solves the issue (at least in my case).
Just follow these instructions: https://unix.stackexchange.com/questions/416912/why-can-i-not-remove-this-dkms-module

**Comment by lolo101** [comment] 2018-07-30 22:29
Ok thank you !

**Closed as completed by lolo101** 2018-07-30 22:29 UTC
